obj-m := rpi-dpidac.o

all:
        make -C /lib/modules/6.1.69-1-rpi-ARCH/build M=/home/pi/build/rpi-dpidac modules

clean:
        make -C /lib/modules/6.1.69-1-rpi-ARCH/build M=/home/pi/build/rpi-dpidac clean
